version: "2"

terraform_config_roots:
  - name: "Campaign tests"
    path: .
    default_file: main.tf
    var_file: vars.tf
    # campaign_config:
    #   state_file_config:
    #     s3:
    #       path: s3://campaigns-terraform-state/terraform.tfstate
    context:
      ans1: "foo"
      production: "false"
    environments:
      - name: dev
        tfvars_file: dev.tfvars
      - name: prod
        tfvars_file: prod.tfvars
        context:
          production: "true"

  - name: "Campaign test cfroot"
    path: test_dir
    default_file: main.tf
    var_file: vars.tf

