name: Manually Triggered State 
on:
  workflow_dispatch:
    inputs:
      repoURL:
        description: 'full URL for the repo associated with the state file'
        required: true 
      configRootPath:
        description: 'config root path'
        required: true
      tf_state_directory:
        description: 'Path from repo root to the directory containing the tf state file to use'
        required: false
        default: 'tf-state-files'
      stateFileName:
        description: 'filename for specific state to evaluate'
        required: false
        default: 'state'
      docker_tag:
        description: 'tag of the resourcely-cli Docker image to use'
        required: false
        default: 'latest'
      resourcely_api_host:
        description: 'url for the resourcely api'
        required: false
        default: "https://api.dev.resourcely.io"
      resourcely_api_token:
        description: 'api to access resourcely api'
        required: true

jobs:
  resourcely-state-eval:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Evaluate State With Resourcely Guardrails
        shell: bash
        if: success()
        run: |
          docker pull ghcr.io/resourcely-inc/resourcely-cli:${{ inputs.docker_tag }}
          docker run --rm \
            -v "$(pwd)/${{ inputs.tf_state_directory}}:/data/tf-state-files" \
            -e RESOURCELY_API_TOKEN="${{ inputs.resourcely_api_token }}" \
            -e RESOURCELY_BETA_FEATURES=BETA_FEATURE_CAMPAIGNS \
            ghcr.io/resourcely-inc/resourcely-cli:${{ inputs.docker_tag }} evaluate_state \
            --api_host "${{ inputs.resourcely_api_host }}" \
            --state_file "/data/tf-state-files/${{inputs.stateFileName}}.tfstate" \
            --repo_url "${{inputs.repoURL}}"  \
            --config_root_path "${{inputs.configRootPath}}" \ 
            --publish_findings true \
            --log ${{ runner.debug == '1' && 'debug' || 'info' }}
